### ISSUE TITLE
- [ ] Implementación en el Frontend haciendo uso de ReactJS evidenciando la navegación de acuerdo con los prototipos de alta fidelidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo2_sa_ppi2020#15]

**Comment by JohnFlorez25** [comment]
@JheinyGil @paulag290 @Valentina090 para dentro 8 días deben evidenciar avances en esta actividad donde tengan las interfaces en REACTJS de lo que se validó en el prototipo en alta fidelidad y recomendaciones de los jurados en la socialización.
El código debe estar en el repositorio del proyecto (o sea este repositorio) validar con la profesora @jennymontoya1001 
![evidencia-repositorio](https://user-images.githubusercontent.com/22262727/94057264-fed42000-fda4-11ea-9f99-55bdd73f9e21.jpeg)
 para que les ayuden a realizar este proceso , les dejo un ejemplo de lo que se debe ir evidenciando.

**Comment by paulag290** [comment]
Buenas tardes, @JohnFlorez25 ya subí los códigos de las pantallas de ReactJS que me corresponden.

**Comment by Valentina090** [comment]
Buenas tardes, @JohnFlorez25 ya subí los códigos de las pantallas de ReactJS que me corresponden.

**Comment by JheinyGil** [comment]
Buenas noches, @JohnFlorez25 ya subí los códigos de las pantallas de ReactJS que me corresponden.

**Comment by JheinyGil** [comment]
Buenas tardes, @JohnFlorez25 ya el vídeo se encuentra en YouTube, el link está en la Wiki pero igualmente lo dejo aquí https://youtu.be/FXdiOpdXmFY
