### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo2_sa_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@JheinyGil @paulag290 @Valentina090 para dentro de 8 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con la profesora Jenny y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo
![modelo-e-r](https://user-images.githubusercontent.com/22262727/94057324-13181d00-fda5-11ea-88d0-9b600fe87c77.png)

**Comment by paulag290** [comment]
Hola, ya se encuentra en la wiki la evidencia del Modelo entidad relación.
