### ISSUE TITLE
- [ ] Definir los servicios del Backend que se deben implementar de acuerdo con las reglas de negocio. (Objeto JSON)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo2_sa_ppi2020#17]

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @JheinyGil @paulag290 @Valentina090  El siguiente formato se especifica la estructura de como deben evidenciar cada uno de los servicios backend que van a ser consumidos desde el frontend 
[Formato Definición de los servicios backend.docx](https://github.com/JohnFlorez25/equipo2_sa_ppi2020/files/5418155/Formato.Definicion.de.los.servicios.backend.docx)
<img width="739" alt="formato-backend" src="https://user-images.githubusercontent.com/22262727/96769189-65e4f480-13a4-11eb-82a0-22be918da3d1.png">

**Comment by JheinyGil** [comment]
@JohnFlorez25 @jennymontoya1001 buenas, el documento de la definición de servicios Backend ya se encuentra vinculado a la wiki.
