### ISSUE TITLE
- [ ] Construcción de la BD haciendo uso de MySQL

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo2_sa_ppi2020#19]

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @JheinyGil @paulag290 @Valentina090 crear una carpeta llamada **bd** en el repositorio donde este la evidencia de los scripts de la base de datos implementada

**Comment by JheinyGil** [comment]
@JohnFlorez25 @jennymontoya1001 Buenas tardes, el script de la Construcción de la BD haciendo uso de MySQL ya se encuentra en la wiki e igualmente la carpeta BD ya está creada con el archivo incluido.
